import React from "react";
import Image from "next/image";

export default function page() {
  return (
    <ul className="grid grid-cols-2 gap-4 md:grid-cols-3">
      <li>
        <Image
          src="/img/img-1.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-2.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-3.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-4.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-5.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-6.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-7.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-8.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-9.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-10.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-11.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-12.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-13.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-14.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-15.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-16.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
      <li>
        <Image
          src="/img/img-17.JPG"
          alt="Image"
          width={200}
          height={200}
          className="w-full"
          priority
        />
      </li>
    </ul>
  );
}
